### ISSUE TITLE
API key validated when first entered, but then cannot be saved

### ISSUE THREAD

**Issue by ToddAu** [alessandrotesoro/Easy-Peasy-MailChimp-Ajax-Form#1]
I just installed Easy Mail Chimp Forms v5.3.1, and I am having issues getting the plugin to recognize the Mail Chimp API key (Wordpress v4.1). When I cut/paste the API key from Mail Chimp, the plugin settings page confirms the key is valid with a green check mark. When I click to "save",  an error message is displayed — "Sorry, that is an invalid MailChimp API key. Please check the error log on the debug options tab for further information". On the debug screen, I see "Invalid Mail Chimp API key" with a date of "Dec. 10th, 2014 - 11:06:14am". I would love to use this plugin, and any insight would be great.

**Comment by alessandrotesoro** [comment]
This is the repository for this plugin https://wordpress.org/plugins/easy-peasy-mailchimp-ajax-form/ 

You're using a different plugin completely unrelated to me or the "Easy Peasy MailChimp Ajax Form" plugin. Contact the author of your plugin.
